### ISSUE TITLE
How about create a link named and-let*.sls for and-let%2a.sls?

### ISSUE THREAD

**Issue by Saigut** [fedeinthemix/chez-srfi#1]
For Chez Scheme to using (import (:2 and-let*)), How about create a link named and-let*.sls for and-let%2a.sls via link-dirs.chezscheme.sps?

**Comment by fedeinthemix** [comment]
The link is created when you run "make" or "make build". You can then
import the library with '(import (srfi :2 and-let*))' or '(import (srfi
:2))'. If something is wrong try with "make clean" and try again.

**Comment by Saigut** [comment]
I didn't check the makefile. Thanks for replying.
