### ISSUE TITLE
equal sign “::=” at line 34 "chezversion ::=..." of Makefile should be ":="?

### ISSUE THREAD

**Issue by Saigut** [fedeinthemix/chez-srfi#2]
I find the equal sign “::=” at line 34 "chezversion ::=..." of Makefile cause `make` fail.
Isn't this should be `:=` ?

**Comment by fedeinthemix** [comment]
According to the GNU make manual "::=" is defined in the POSIX standard,
while ":=" is a GNU make only extension. In GNU make the two are equivalent.

https://www.gnu.org/software/make/manual/html_node/Flavors.html#Flavors

**Comment by Saigut** [comment]
My version of make is 3.81, it's too old to support this `::=` form.
